# Generated by Django 4.0.2 on 2022-02-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=50, unique=True)),
                ('descipcion', models.CharField(blank=True, max_length=255)),
                ('slug', models.CharField(unique=True, max_length=100)),
            ],
        ),
    ]
