# Generated by Django 3.2.8 on 2022-03-02 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventario',
            old_name='descipcion',
            new_name='descripcion',
        ),
    ]
