# Generated by Django 3.2.8 on 2022-03-02 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_rename_descipcion_inventario_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='slug',
        ),
    ]
