# Generated by Django 3.2.8 on 2022-03-22 15:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(blank=True, max_length=255, unique=True)),
                ('date_joined', models.DateField(default=datetime.datetime.now)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('numero_mesa', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('Pagado', 'Pagado'), ('En espera', 'En espera')], default='', max_length=10)),
                ('comentarios', models.CharField(blank=True, default='', max_length=255)),
                ('efectivo_caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.general')),
            ],
        ),
    ]
