# Generated by Django 3.2.8 on 2022-03-22 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carta', '0001_initial'),
        ('cuenta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='mesero',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sale',
            name='producto',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='carta.productomenu'),
        ),
    ]
