# Generated by Django 3.2.8 on 2022-03-23 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='efectivo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='sale',
            name='tarjeta',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
