# Generated by Django 3.2.8 on 2022-03-15 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('efectivo_caja', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('date_joined', models.DateField(default=datetime.datetime.now)),
                ('ingreso_efectivo', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('ingreso_tarjeta', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('numero_mesas', models.IntegerField(default=0, max_length=3)),
                ('propina_tarjeta', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
            ],
        ),
    ]
