# Generated by Django 3.2.8 on 2022-03-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general',
            name='numero_mesas',
            field=models.IntegerField(default=0),
        ),
    ]
