# Generated by Django 3.2.8 on 2022-03-11 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_promocion', models.CharField(max_length=200, unique=True)),
                ('precio', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='photos/promo')),
                ('producto', models.ForeignKey(default='Hamburguesa', on_delete=django.db.models.deletion.CASCADE, to='carta.productomenu')),
            ],
        ),
        migrations.CreateModel(
            name='ProductosDias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('01', 'Lunes'), ('02', 'Martes'), ('03', 'Miercoles'), ('04', 'Jueves'), ('05', 'Viernes'), ('06', 'Sabado'), ('07', 'Domingo')], max_length=10)),
                ('producto1', models.ForeignKey(default='Hamburguesa', on_delete=django.db.models.deletion.CASCADE, to='carta.productomenu')),
                ('promocion1', models.ForeignKey(default='Jueves Godin', on_delete=django.db.models.deletion.CASCADE, to='promocion.promocion')),
            ],
        ),
    ]
