# Generated by Django 3.2.8 on 2022-03-11 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carta', '0001_initial'),
        ('promocion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocion',
            name='producto',
        ),
        migrations.AddField(
            model_name='promocion',
            name='producto',
            field=models.ManyToManyField(default='Hamburguesa', through='promocion.ProductosDias', to='carta.ProductoMenu'),
        ),
    ]
