# Generated by Django 3.2.8 on 2022-03-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocion', '0003_auto_20220314_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='productosdias',
            name='precio_descuento',
            field=models.IntegerField(blank=True, default=20),
        ),
    ]
