# Generated by Django 3.2.8 on 2022-03-24 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocion', '0003_auto_20220322_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='productosdias',
            name='cantidad',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
