# Generated by Django 3.2.8 on 2022-03-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocion', '0005_remove_promocion_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productosdias',
            name='dia',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=10),
        ),
    ]
