# Generated by Django 3.2.8 on 2022-03-14 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocion', '0006_alter_productosdias_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='photos/promo'),
        ),
    ]
